/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Patient;

/**
 *
 * @author rishabhkaushick
 */
public class PatientFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientFormPanel
     */
    
    private JPanel bottomPanel;
    public PatientFormPanel(JPanel bottomPanel) {
        this.bottomPanel = bottomPanel;
        initComponents();
    }

    public String profilePicName="";// this is the global variable for the name of image uploaded by user.
    public File profilePicture;     // this is the global variable for the profile image uploaded by user.
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        patientTypeLabel = new javax.swing.JLabel();
        patientTypeComboBox = new javax.swing.JComboBox<>();

        mainPanel.setBackground(new java.awt.Color(0, 153, 204));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        titleLabel.setFont(new java.awt.Font("Arima Koshi", 1, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Patient Registration Form");
        titleLabel.setToolTipText("");
        titleLabel.setPreferredSize(new java.awt.Dimension(358, 46));

        firstNameLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");

        lastNameTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age");

        ageTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N

        submitButton.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        patientTypeLabel.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        patientTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientTypeLabel.setText("Patient Type");

        patientTypeComboBox.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        patientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergency", "Appointment", "Follow-up Appointment", "Walk In" }));
        patientTypeComboBox.setSelectedIndex(-1);
        patientTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(patientTypeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patientTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ageTextField)
                                    .addComponent(firstNameTextField))))
                        .addGap(225, 225, 225)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(51, 51, 51)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(52, 52, 52)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientTypeLabel)
                    .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(submitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    // helper function to update most relevant title of the popup title
    public String updatePopupTitle(String popupTitle, String newPopupTitle){
        if (popupTitle.equals("")){
            //this means that this is the first error. Therefore we display a specific error message in the title
            return newPopupTitle;
        } else{
            //this means that there are multiple errors in the form submission
            return "Please Fix Below Erros:";
        }
    }
    
    // helper funtion to update all the errors present in the popup message
    public String updatePopupMessage(String popupMessage, String newPopupMessage){
        if(popupMessage.equals("")){
            return newPopupMessage;
        } else{
            return popupMessage+"\n"+newPopupMessage;
        }
    }
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        // Now need to get the data into the User
        
        // adding error handling string messages here
        String popupTitle="", popupMessage="";

        // Using Regex to Validate the User Inputs
        String regexString = "[(')a-zA-z]*";
        String numericString = "[0-9]*";
        String emailString = "([a-zA-Z0-9.!#$%&'*+=?^_`{|}~-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*)";
        Pattern regexNamePattern = Pattern.compile(regexString);
        Pattern regexAgePattern = Pattern.compile(numericString);

        Boolean errorFlag = false;

        try{
            // First Name Validations
            // testing if the first name is blank
            if(firstNameTextField.getText().isBlank()){
                // first name is mandatory - popup should say that it is required.
                popupTitle = updatePopupTitle(popupTitle, "First Name Required!");
                popupMessage = updatePopupMessage(popupMessage, "Please enter your first name to proceed.");
                errorFlag = true;
            } // testing if first name contains any special characters
            else if((!regexNamePattern.matcher(firstNameTextField.getText()).matches())){
                // if first name is not blank - it should not have any special characters
                popupTitle = updatePopupTitle(popupTitle, "Special Characters/ Numbers Not Allowed in First Name");
                popupMessage = updatePopupMessage(popupMessage, "Sorry, special characters or numbers are not allowed in the First Name.");
                errorFlag = true;
            }

            // Last Name Validations
            // last name cannot contain special characters as well (except for ' for names like D'Souza
                if(!regexNamePattern.matcher(lastNameTextField.getText()).matches()){
                    popupTitle = updatePopupTitle(popupTitle, "Numbers / Special Characters Not Allowed in Last Name");
                    popupMessage = updatePopupMessage(popupMessage, "Sorry, special characters or numbers are not allowed in the Last Name.");
                    errorFlag = true;
                }

                // Age validations
                if(ageTextField.getText().isBlank()){
                    popupTitle = updatePopupTitle(popupTitle, "Age is Required!");
                    popupMessage = updatePopupMessage(popupMessage, "Please enter your age to proceed.");
                    errorFlag = true;
                }
                else if(!regexAgePattern.matcher(ageTextField.getText()).matches()){
                    // not a number
                    popupTitle = updatePopupTitle(popupTitle, "Age Should a Numeric Value");
                    popupMessage = updatePopupMessage(popupMessage, "Please enter the value of your age in numeric values between 1 - 130");
                    errorFlag = true;
                } else if (ageTextField.getText().equals("0")){
                    // age cannot be 0
                    popupTitle = updatePopupTitle(popupTitle, "Age Cannot be 0");
                    popupMessage = updatePopupMessage(popupMessage, "Please enter a valid age between 1 - 130");
                    errorFlag = true;
                } else if (Integer.parseInt(ageTextField.getText()) > 130){
                    // age greater than 130 is not possible - update the error message
                    popupTitle = updatePopupTitle(popupTitle, "Too Old!!");
                    popupMessage = updatePopupMessage(popupMessage, "The Age you entered is too old to live, please re-check and enter your real age to proceed.");
                    errorFlag = true;
                }
                
                // Patient Type Validations
                if(patientTypeComboBox.getSelectedIndex() == -1){
                    // this means the user has not selected any values --> throw error
                    popupTitle = updatePopupTitle(popupTitle, "Invalid Patient Type!");
                    popupMessage = updatePopupMessage(popupMessage, "Please select a valid patient type from the dropdown to proceed.");
                    errorFlag = true;
                }
                

                if(popupTitle.equals("") && popupMessage.equals("") && (!errorFlag)){
                    popupTitle = "Submitted!";
                    popupMessage = "Your entry has been recorded!"+"\n"
                    +"Name: "+firstNameTextField.getText()+" "+lastNameTextField.getText()+"\n"
                    +"Age: "+ageTextField.getText()+"\n"
//                    +"Email:"+emailTextField.getText()+"\n"
//                    +"Message: "+"\n"+messageTextArea.getText()+"\n"
                    +"Image:"+this.profilePicName+"\n";

                }
                // logging message for debugging
                System.out.println("Popup Title: "+popupTitle);
                System.out.println("Popup Body: "+popupMessage);
                if(errorFlag){
                    // this means there is an error - so displaying the error message with the error icon
                    // System.out.println(System.getProperty("user.dir")+"/src/ui/error_image.jpeg"); // debug
                    JOptionPane.showMessageDialog(this, popupMessage, popupTitle, HEIGHT);
                } else {
                    // no error
                    if(this.profilePicName.isBlank() || this.profilePicName.equals("No Image Uploaded")){
                        // no profile picture
                        // display the details with the success icon
                        // System.out.println(System.getProperty("user.dir")+"/src/ui/success_image.png");
                        // JOptionPane.showMessageDialog(this, popupMessage, popupTitle, HEIGHT, successIcon);
                        // instead of getting a dialog box --> we must put it in the Patient object.
                        Patient patient1 = new Patient();
                        patient1.setFirstName(firstNameTextField.getText());
                        patient1.setLastName(lastNameTextField.getText());
                        patient1.setAge(Integer.parseInt(ageTextField.getText()));
//                        patient1.setEmail(emailTextField.getText());
//                        patient1.setMessage(messageTextArea.getText());
                        
                        // debugging how to get the selected value of the button group
                        //System.out.println(genderButtonGroup.getSelection().getActionCommand());
//                        patient1.setGender(genderButtonGroup.getSelection().getActionCommand());
                        
                        //setting the value of the combobox
//                        System.out.println("Patient Combobox");
//                        System.out.println(patientTypeComboBox.getSelectedItem().toString());
                        patient1.setPatientType(patientTypeComboBox.getSelectedItem().toString());
                        
                        ViewPanel newViewPanel = new ViewPanel(patient1);
                        this.bottomPanel.add(newViewPanel);
                        CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
                        layout.next(this.bottomPanel);
                        
                    } else {
                        // profile picture loaded by the user
                        // System.out.println(this.profilePicture.getAbsolutePath());
                        // JOptionPane.showMessageDialog(this, popupMessage, popupTitle, HEIGHT, profilePicIcon);
                        // instead of getting a dialog box --> we must put it in the Patient object.
                        // and then view the ViewPane button
                        
                        // Here the patient record must be initialized and it should go to the View Panel page
                        Patient patient1 = new Patient();
                        patient1.setFirstName(firstNameTextField.getText());                        
                        patient1.setLastName(lastNameTextField.getText());
                        patient1.setAge(Integer.parseInt(ageTextField.getText()));
                        patient1.setPatientType(patientTypeComboBox.getSelectedItem().toString());
                        ViewPanel newViewPanel = new ViewPanel(patient1);
                        this.bottomPanel.add(newViewPanel);
                        CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
                        layout.next(this.bottomPanel);                         
                        
                    }
                }
            } catch(Exception e){
                JOptionPane.showMessageDialog(this, "Sorry, but there was an error while submitting! Please see the below error details:"+"\n"+e, "Oops!", HEIGHT);
            }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void patientTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> patientTypeComboBox;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
