/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import utility.DatabaseConnector;

/**
 *
 * @author rishabhkaushick
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    
    private ArrayList <Patient> patients;
    private Patient selectedPatient;
    
    
    public ViewPanel(){
        initComponents();
//        populatePatientData();
        // now we need to comment above line
        // and uncomment the below line
         populatePatientTable();
         clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        patientTypeLabel = new javax.swing.JLabel();
        patientTypeComboBox = new javax.swing.JComboBox<>();
        iconLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        editPatientLabel = new javax.swing.JLabel();
        deleteRowButton = new javax.swing.JButton();
        editRowButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(0, 204, 102));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        titleLabel.setFont(new java.awt.Font("Arima Koshi", 1, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Registered Patient's View");
        titleLabel.setToolTipText("");
        titleLabel.setPreferredSize(new java.awt.Dimension(358, 46));

        firstNameLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");

        lastNameTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Annai MN", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age");

        ageTextField.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N

        patientTypeLabel.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        patientTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientTypeLabel.setText("Patient Type");

        patientTypeComboBox.setFont(new java.awt.Font("Annai MN", 0, 13)); // NOI18N
        patientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emergency", "Appointment", "Follow-up Appointment", "Walk In" }));
        patientTypeComboBox.setSelectedIndex(-1);
        patientTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypeComboBoxActionPerformed(evt);
            }
        });

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Age", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientTable);
        if (patientTable.getColumnModel().getColumnCount() > 0) {
            patientTable.getColumnModel().getColumn(0).setResizable(false);
            patientTable.getColumnModel().getColumn(1).setResizable(false);
            patientTable.getColumnModel().getColumn(2).setResizable(false);
            patientTable.getColumnModel().getColumn(3).setResizable(false);
        }

        editPatientLabel.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        editPatientLabel.setForeground(new java.awt.Color(255, 255, 255));
        editPatientLabel.setText("Edit Patient");

        deleteRowButton.setText("Delete Selected Row");
        deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowButtonActionPerformed(evt);
            }
        });

        editRowButton.setText("Edit Selected Row");
        editRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRowButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconLabel)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(deleteRowButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageLabel)
                                    .addComponent(patientTypeLabel)
                                    .addComponent(lastNameLabel)
                                    .addComponent(firstNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveButton)
                                    .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(editPatientLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(editRowButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editRowButton)
                            .addComponent(deleteRowButton))
                        .addGap(52, 52, 52)
                        .addComponent(editPatientLabel)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(iconLabel))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageLabel))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientTypeLabel))
                                .addGap(18, 18, 18)
                                .addComponent(saveButton))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void patientTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypeComboBoxActionPerformed

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = patientTable.getSelectedRow();
        
        // validating if the user has selected a row before hitting delete
        if(selectedRowIndex == -1){
            // user has not selected a row
            JOptionPane.showMessageDialog(this, "Please select the user first!", "Oops, unable to delete!", HEIGHT);
        } else {
            try{
                this.selectedPatient = this.patients.get(selectedRowIndex);
                DatabaseConnector.deleteUser(selectedPatient);
                JOptionPane.showMessageDialog(null, "Patient Deleted Successfully!", "Success!", HEIGHT);
                clearFields();
                populatePatientTable();
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Unable to delete patient!", HEIGHT);
            }
        }
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void editRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRowButtonActionPerformed
        // TODO add your handling code here:
        // populate patient data function needs to be called if selected
        int selectedRowIndex = patientTable.getSelectedRow();
        
        // validating if the user has selected a row before hitting edit
        if(selectedRowIndex == -1){
            // user has not selected a row
            JOptionPane.showMessageDialog(this, "Please select the user first!", "Oops, unable to edit!", HEIGHT);
        } else {
            try{
                this.selectedPatient = this.patients.get(selectedRowIndex);
                populatePatientData(selectedPatient);
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_editRowButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        // first  validation for new patient
        // adding error handling string messages here
        String popupTitle="", popupMessage="";

        // Using Regex to Validate the User Inputs
        String regexString = "[(')a-zA-z]*";
        String numericString = "[0-9]*";
        Pattern regexNamePattern = Pattern.compile(regexString);
        Pattern regexAgePattern = Pattern.compile(numericString);

        Boolean errorFlag = false;

        try{
            // First Name Validations
            // testing if the first name is blank
            if(firstNameTextField.getText().isBlank()){
                // first name is mandatory - popup should say that it is required.
                popupTitle = updatePopupTitle(popupTitle, "First Name Required!");
                popupMessage = updatePopupMessage(popupMessage, "Please enter your first name to proceed.");
                errorFlag = true;
            } // testing if first name contains any special characters
            else if((!regexNamePattern.matcher(firstNameTextField.getText()).matches())){
                // if first name is not blank - it should not have any special characters
                popupTitle = updatePopupTitle(popupTitle, "Special Characters/ Numbers Not Allowed in First Name");
                popupMessage = updatePopupMessage(popupMessage, "Sorry, special characters or numbers are not allowed in the First Name.");
                errorFlag = true;
            }

            // Last Name Validations
            // last name cannot contain special characters as well (except for ' for names like D'Souza
            if(!regexNamePattern.matcher(lastNameTextField.getText()).matches()){
                popupTitle = updatePopupTitle(popupTitle, "Numbers / Special Characters Not Allowed in Last Name");
                popupMessage = updatePopupMessage(popupMessage, "Sorry, special characters or numbers are not allowed in the Last Name.");
                errorFlag = true;
            }

            // Age validations
            if(ageTextField.getText().isBlank()){
                popupTitle = updatePopupTitle(popupTitle, "Age is Required!");
                popupMessage = updatePopupMessage(popupMessage, "Please enter your age to proceed.");
                errorFlag = true;
            }
            else if(!regexAgePattern.matcher(ageTextField.getText()).matches()){
                // not a number
                popupTitle = updatePopupTitle(popupTitle, "Age Should a Numeric Value");
                popupMessage = updatePopupMessage(popupMessage, "Please enter the value of your age in numeric values between 1 - 130");
                errorFlag = true;
            } else if (ageTextField.getText().equals("0")){
                // age cannot be 0
                popupTitle = updatePopupTitle(popupTitle, "Age Cannot be 0");
                popupMessage = updatePopupMessage(popupMessage, "Please enter a valid age between 1 - 130");
                errorFlag = true;
            } else if (Integer.parseInt(ageTextField.getText()) > 130){
                // age greater than 130 is not possible - update the error message
                popupTitle = updatePopupTitle(popupTitle, "Too Old!!");
                popupMessage = updatePopupMessage(popupMessage, "The Age you entered is too old to live, please re-check and enter your real age to proceed.");
                errorFlag = true;
            }

            // Patient Type Validations
            if(patientTypeComboBox.getSelectedIndex() == -1){
                // this means the user has not selected any values --> throw error
                popupTitle = updatePopupTitle(popupTitle, "Invalid Patient Type!");
                popupMessage = updatePopupMessage(popupMessage, "Please select a valid patient type from the dropdown to proceed.");
                errorFlag = true;
            }


            if(popupTitle.equals("") && popupMessage.equals("") && (!errorFlag)){
                popupTitle = "Edit Successful!";
                popupMessage = "Your update has been recorded!"+"\n"
                +"Name: "+firstNameTextField.getText()+" "+lastNameTextField.getText()+"\n"
                +"Age: "+ageTextField.getText()+"\n"
                +"Patient Type:"+patientTypeComboBox.getSelectedItem().toString()+"\n";

            }
            // logging message for debugging
            System.out.println("Popup Title: "+popupTitle);
            System.out.println("Popup Body: "+popupMessage);
            if(errorFlag){
                JOptionPane.showMessageDialog(this, popupMessage, popupTitle, HEIGHT);
            } else {
                // no error
                // Here the patient record must be initialized and it should go to the View Panel page
                // getting the values from the text fields into a new patient object
                Patient newPatient = new Patient();
                newPatient.setFirstName(firstNameTextField.getText());
                newPatient.setLastName(lastNameTextField.getText());
                newPatient.setAge(Integer.parseInt(ageTextField.getText()));
                newPatient.setPatientType(patientTypeComboBox.getSelectedItem().toString());
                
                // here we will update the table
                DatabaseConnector.editUser(this.selectedPatient, newPatient);
                JOptionPane.showMessageDialog(this, popupMessage, popupTitle, HEIGHT);
                clearFields();
                populatePatientTable();
                
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sorry, but there was an error while editing! Please see the below error details:"+"\n"+e, "Oops!", HEIGHT);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // helper function to update most relevant title of the popup title
    public String updatePopupTitle(String popupTitle, String newPopupTitle){
        if (popupTitle.equals("")){
            //this means that this is the first error. Therefore we display a specific error message in the title
            return newPopupTitle;
        } else{
            //this means that there are multiple errors in the form submission
            return "Please Fix Below Erros:";
        }
    }
    
    // helper funtion to update all the errors present in the popup message
    public String updatePopupMessage(String popupMessage, String newPopupMessage){
        if(popupMessage.equals("")){
            return newPopupMessage;
        } else{
            return popupMessage+"\n"+newPopupMessage;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JLabel editPatientLabel;
    private javax.swing.JButton editRowButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable patientTable;
    private javax.swing.JComboBox<String> patientTypeComboBox;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void populatePatientTable(){
        try{
            this.patients = DatabaseConnector.getAllPatients();
            DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            model.setRowCount(0);
            for(Patient p1 : patients){
                Object [] patientRow  = new Object[5];
                patientRow[0] = p1.getId();
                patientRow[1] = p1.getFirstName();
                patientRow[2] = p1.getLastName();
                patientRow[3] = p1.getAge();
                patientRow[4] = p1.getPatientType();
                model.addRow(patientRow);
            }
            clearFields();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error!", HEIGHT);
        }
    }
    private void populatePatientData(Patient p1) {
        // This function is resposible to set the fields with the values in the Patient data
//        System.out.println("Entering populatePatientData function"); // this is for debugging
        firstNameTextField.setText(p1.getFirstName());
        lastNameTextField.setText(p1.getLastName());
        ageTextField.setText(Integer.toString(p1.getAge()));
        // setting the combobox
        patientTypeComboBox.setSelectedItem(p1.getPatientType());
    }
    
    private void clearFields(){
        // removing the text in the edit section - first name, last name, age, patient type
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        ageTextField.setText(null);
        patientTypeComboBox.setSelectedIndex(-1);
    }
}
